services:
  mc:
    image: itzg/minecraft-server:stable-java25
    pull_policy: always
    container_name: test
    restart: unless-stopped

    tty: true
    stdin_open: true

    ports:
      # Java Edition
      - "25565:25565/tcp"

      # Bedrock Edition through Geyser
      - "19132:19132/udp"

    environment:
      EULA: "TRUE"

      TYPE: "FABRIC"
      VERSION: "26.1.2"
      FABRIC_LOADER_VERSION: "0.19.3"

      MEMORY: "5120M"
      MAX_PLAYERS: "10"

      MOTD: "Welcome to R9 Data Labs Minecraft Server"
      SERVER_NAME: "R9_Data_Labs"
      TZ: "America/New_York"

      DIFFICULTY: "normal"
      GAMEMODE: "survival"
      FORCE_GAMEMODE: "true"
      LEVEL: "R9_W1"

      ONLINE_MODE: "TRUE"

      MODRINTH_PROJECTS: |
        fabric-api
        geyser:beta
        floodgate
        lithium?
        ferrite-core?
        chunky?
        towns-and-towers?
        structory?
        leaves-be-gone?
        universal-graves?
        betterdays?
        clumps?
        servercore?
        better-boat-movement?
        fasterladderclimbing?
        nocroptrample?
        dungeons-and-taverns?
        towns-and-towers?

      MODRINTH_PROJECTS_DEFAULT_VERSION_TYPE: "release"
      MODRINTH_DOWNLOAD_DEPENDENCIES: "required"

    volumes:
      - ./data:/data
